name: Vue Build and Code Quality

on:
  push:
    branches: [ master ]


jobs:
  compile_md:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.2

    - name: npm lint
      run: |
        npm install
        npm run lint
        npm run build
